ConfigVersion: 3.8
#----------------#
#Dafault Settings#
#----------------#
ops-name-color: 4
NickNamePrefix: '~'
JoinSpawnTeleport: true
#----------------#
#Chat Settings!  #
#----------------#
ChatFormat: '{Group} &e{Player} &2>> &f{Message}'
JoinMessage: '&e{Group} {Player} joined the Game'
FirstJoinMessage: '&e{Group} {Player} is the server joined for the first time!'
LeaveMessage: '&e{Group} {Player} left the Game'
#-------------------#
#ExplosionEffects Settings#
#-------------------#
PhysicExplosion: false
#-----------------#
# Logger Settings #
#-----------------#
Logger: true
LoggerFile: 'plugins/EssentialsGreen/logger.log'
PlayerJoinLog: true
PlayerQuitLog: true
ChatLog: true
CommandLog: true
BlockBreakLog: false
BlockPlaceLog: false
ChangeWorldLog: true