name: EssentialsGreen
version: 3.8
authors: [CCBlueX]

main: me.noip.ccbluex.EssentialsGreen.EssentialsGreen
commands:
     EssentialsGreen:
          usage: /<command>
          aliases: [eg]
     gamemode:
          usage: /gamemode <Mode> [Player]
          aliases: [gm]
     tp:
          usage: /tp <target> [other target]
     spawn:
          usage: /spawn [Target]
     setspawn:
          usage: /setspawn
     kick:
          usage: /kick <Player> <Reason>
     ban:
          usage: /ban <Player> <Reason>
     unban:
          usage: /unban <Player>
     banlist:
          usage: /banlist
     give:
          usage: /give <Player> <ID> [Ammount]
     msg:
          usage: /msg <Player> <Message>
     time:
          usage: /time <set|add> <Time>
     xp:
          usage: /xp <set|add> <XP>
     broadcast:
          usage: /broadcast <Message>
          aliases: [b,bc]
     say:
          usage: /say <Message>
     kill:
          usage: /kill <Player|@a|@e <World>>
     fly:
          usage: /fly [Player]
     speed:
          usage: /speed [Number] [Player]
     invsee:
          usage: /invsee <Player>
     heal:
          usage: /heal [Player]
     nick:
          usage: /nick <Name|off>
     setworldspawn:
          usage: /setworldspawn
     seed:
          usage: /seed [World]
     clear:
          usage: /clear [Player]
     list:
          usage: /list
     defaultgamemode:
          usage: /defaultgamemode <Mode>
     stop:
          usage: /stop
     reload:
          usage: /reload
          aliases: [rl]
     whitelist:
          usage: /whitelist <command>
     warp:
          usage: /warp <Command>
     skull:
          usage: /skull [Owner]
     spawnmob:
          usage: /spawnmob <mob> [Ammount]
     spawnpoint:
          usage: /spawnpoint
     effect:
          usage: /effect <Player> <Effect> [Time] [Level]
     asConsole:
          usage: /asConsole <Command...>
          aliases: [ac]
     tpall:
          usage: /tpall [Target]
#    tempban:
#         usage: /tempban
#         aliases: [tempb, temb, tban, tb]
     vanish:
          usage: /vanish [Player]
          aliases: [v]
     chat:
          usage: /chat <Commands...>
#    backup:
#         usage: /backup
     servermanage:
          usage: /servermanage
          aliases: [stop,reload,rl]