ConfigVersion: 3.6
#----------------#
#Dafault Settings#
#----------------#
AutoUpdate: true
ops-name-color: 4
NickNamePrefix: '~'
JoinSpawnTeleport: true
#----------------#
#Chat Settings!  #
#----------------#
ChatFormat: '{Group} &e{Player} &2>> &f{Message}'
JoinMessage: '&e{Group} {Player} joined the Game'
FirstJoinMessage: '&e{Group} {Player} is the server joined for the first time!'
LeaveMessage: '&e{Group} {Player} left the Game'
#--------------------#
# Ban | Kick Messages#
#--------------------#
Ban-Message: '&4You have bannend from this Server!'
Kick-Prefix: '&e[Kick]&3 '
#-------------------#
#ExplosionEffects Settings#
#-------------------#
PhysicExplosion: false
#----------------#
#NickNameBlackList#
#----------------#
NickNames:
- <Names>
#----------------------#
# ChunkLoader Settings #
#----------------------#
ChunkLoaderEnable: true
ChunkLoaderBlock: ENCHANTMENT_TABLE