# EssentialsGreen Config [By Marco606598 [German Developer] YT Channel : https://www.youtube.com/channel/UCeuZKKGXKe8wUw2R5FB5fxA]

#----------------#
#Dafault Settings#
#----------------#
ops-name-color: 4
NickNamePrefix: ''
JoinSpawnTeleport: true
AutoUpdate: true
#----------------#
#Chat Settings!  #
#----------------#
ChatFormat: '{Group} &e{Player} &2>> &f{Message}'
JoinMessage: '&e{Group} {Player} joined the Game'
FirstJoinMessage: '&e{Group} {Player} is the server joined for the first time!'
LeaveMessage: '&e{Group} {Player} left the Game'
#--------------------#
# Ban | Kick Messages#
#--------------------#
Ban-Prefix: '&e[Ban]&3 '
Kick-Prefix: '&e[Kick]&3 '
Ban-JoinBrodcast: '&e{Player} is Banned! Reason : {Reason}'
#-------------------#
#Protection Settings#
#-------------------#
CreeperBlockDamage: true
TnTBlockDamage: true
WhitherSkullBlockDamage: true
Ender_CrystalBlockDamage: true
FireballBlockDamage: true
PhysicExplosion: false
#----------------#
#CommandBlacklist#
#Bypass Permmision : EssentilasGreen.CommandBlacklist.bypass#
#----------------#
CommandBlockMessage: '&2[EG]&e Command Blocked!'
Commands:
- /op
CommandBlackListBypassPlayerList:
- <Player>
#----------------#
#NickNameBlackList#
#----------------#
NickNames:
- <Names>